# Generated by Django 6.0.2 on 2026-02-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
