# Generated by Django 6.0.2 on 2026-02-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_edited_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='edited_at',
        ),
    ]
