# Generated by Django 6.0.2 on 2026-03-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_notification_edited_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='wallet',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
