# Generated by Django 6.0.2 on 2026-03-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_transaction_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='balance_after',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='entry_type',
        ),
        migrations.AddField(
            model_name='ledger',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEPOSIT', 'Deposit')], default='CREDIT', max_length=7),
        ),
    ]
